version = "2"

[formatters]
enable = ["goimports", "gofumpt"]

[formatters.settings.gofumpt]
module-path = "github.com/asciimoo/hister"

[formatters.settings.goimports]
local-prefixes = ["github.com/asciimoo"]

[linters]
enable = ["modernize"]

[linters.exclusions]
paths = ["node_modules"]
